# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='class_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
